CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "google_sub" varchar(31) UNIQUE NOT NULL,
  "username" varchar(255) NOT NULL,
  "email" varchar(255) UNIQUE NOT NULL
);

CREATE TABLE "traits" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "code" char(1) UNIQUE NOT NULL,
  "name" varchar(31) NOT NULL,
  "description" varchar(1023) NOT NULL
);

CREATE TABLE "dichotomies" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "index" int UNIQUE NOT NULL,
  "left_trait_id" int UNIQUE NOT NULL,
  "right_trait_id" int UNIQUE NOT NULL
);

CREATE TABLE "personalities" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "code" varchar(7) UNIQUE NOT NULL,
  "name" varchar(31) NOT NULL,
  "description" varchar(1023) NOT NULL
);

CREATE TABLE "questions" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "number" int UNIQUE NOT NULL,
  "prompt" varchar(255) NOT NULL,
  "dichotomy_id" int NOT NULL
);

CREATE TABLE "question_options" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "statement" varchar(255) NOT NULL,
  "question_id" int NOT NULL,
  "trait_id" int NOT NULL
);

CREATE TABLE "assessments" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "user_id" int NOT NULL,
  "completed_at" timestamp
);

CREATE TABLE "assessment_responses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "assessment_id" int NOT NULL,
  "question_id" int NOT NULL,
  "question_option_id" int NOT NULL
);

ALTER TABLE "dichotomies" ADD FOREIGN KEY ("left_trait_id") REFERENCES "traits" ("id");

ALTER TABLE "dichotomies" ADD FOREIGN KEY ("right_trait_id") REFERENCES "traits" ("id");

ALTER TABLE "questions" ADD FOREIGN KEY ("dichotomy_id") REFERENCES "dichotomies" ("id");

ALTER TABLE "question_options" ADD FOREIGN KEY ("question_id") REFERENCES "questions" ("id");

ALTER TABLE "question_options" ADD FOREIGN KEY ("trait_id") REFERENCES "traits" ("id");

ALTER TABLE "assessments" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "assessment_responses" ADD FOREIGN KEY ("assessment_id") REFERENCES "assessments" ("id");

ALTER TABLE "assessment_responses" ADD FOREIGN KEY ("question_id") REFERENCES "questions" ("id");

ALTER TABLE "assessment_responses" ADD FOREIGN KEY ("question_option_id") REFERENCES "question_options" ("id");