name: "InnerLens Deployment Pipeline"

on:
  push:
    branches:
      - main
      - development

jobs:
  terraform:
    permissions:
      id-token: write
      contents: read
    name: "Manage AWS Resources"
    runs-on: ubuntu-latest
    outputs:
      dbhost: ${{ steps.tf_outputs.outputs.dbhost }}
      ec2host: ${{ steps.tf_outputs.outputs.ec2host }}
    defaults:
      run:
        working-directory: terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::229582503298:role/github-oidc
          aws-region: af-south-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.0.1
          terraform_wrapper: false

      - name: Terraform Init
        id: init
        run: terraform init -backend-config="bucket=innerlens-tf-state" -backend-config="key=terraformstate/terraform.tfstate" -backend-config="region=af-south-1"

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Capture Terraform Outputs
        id: tf_outputs
        run: |
          echo "dbhost=$(terraform output -raw db_host)" >> $GITHUB_OUTPUT
          echo "ec2host=$(terraform output -raw ec2_host)" >> $GITHUB_OUTPUT

  build-application:
    name: Package API
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create Build Artifact
        run: |
          mkdir -p build
          cp -r server/ build/
          cp -r client/ build/
          cd build
          zip -r ../innerlens-api.zip .
          
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: innerlens-api
          path: innerlens-api.zip

  deploy-api:
    name: Deploy API to EC2
    permissions:
      id-token: write
      contents: read
    needs:
      - terraform
      - build-application
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::229582503298:role/github-oidc
          aws-region: af-south-1

      - name: Get Secrets from AWS Secrets Manager
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: |
            EC2_PRIVATE_KEY, innerlens-key
            GOOGLE_CLIENT_ID, clientid
            GOOGLE_CLIENT_SECRET, clientsecret
            GOOGLE_REDIRECT_URI, redirecturi
            DATABASE_PORT, dbport
            DATABASE_NAME, dbname
            POSTGRESUSER, postgresuser
            POSTGRESPASSWORD, postgrespass

      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: innerlens-api

      - name: Setup SSH Key
        run: |
          echo "${{ env.EC2_PRIVATE_KEY }}" > innerlens-key.pem
          chmod 400 innerlens-key.pem

      - name: Deploy to EC2
        run: |
          EC2_HOST=${{ needs.terraform.outputs.ec2host }}
          
          scp -o StrictHostKeyChecking=no -i innerlens-key.pem innerlens-api.zip "ubuntu@$EC2_HOST:~/innerlens-api.zip"

          ssh -o StrictHostKeyChecking=no -i innerlens-key.pem "ubuntu@$EC2_HOST" '
            sudo apt update
            sudo apt install -y unzip

            sudo rm -rf ~/innerlens-api
            unzip -o ~/innerlens-api.zip -d ~/innerlens-api
            cd ~/innerlens-api/server

            sudo npm install
            sudo npm install pm2@latest -g

            # create .env file
            echo "GOOGLE_CLIENT_ID=${{ env.GOOGLE_CLIENT_ID }}" > .env
            echo "GOOGLE_CLIENT_SECRET=${{ env.GOOGLE_CLIENT_SECRET }}" >> .env
            echo "GOOGLE_REDIRECT_URI=${{ env.GOOGLE_REDIRECT_URI }}" >> .env
            echo "DATABASE_HOST=${{ needs.terraform.outputs.dbhost }}" >> .env
            echo "DATABASE_PORT=${{ env.DATABASE_PORT }}" >> .env
            echo "DB_NAME=${{ env.DATABASE_NAME }}" >> .env
            echo "DATABASE_USER=${{ env.POSTGRESUSER }}" >> .env
            echo "DATABASE_PASSWORD=${{ env.POSTGRESPASSWORD }}" >> .env

            # start server
            pm2 stop all
            pm2 start server.js --name innerlens
          '

      - name: Setup Nginx Proxy
        run: |
          EC2_HOST=${{ needs.terraform.outputs.ec2host }}
          ssh -o StrictHostKeyChecking=no -i innerlens-key.pem "ubuntu@$EC2_HOST" '  
          sudo apt install -y unzip nginx openssl

          # set up ssl certificate
          sudo mkdir -p /etc/nginx/ssl
          if [ ! -f /etc/nginx/ssl/certificate.crt ] || [ ! -f /etc/nginx/ssl/privatessl.key ]; then
            echo "Generating new self-signed certificate..."
            sudo openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
              -keyout /etc/nginx/ssl/privatessl.key \
              -out /etc/nginx/ssl/certificate.crt \
              -subj "/C=US/ST=State/L=City/O=Organization/CN=*.amazonaws.com"
            sudo chmod 600 /etc/nginx/ssl/privatessl.key
          else
            echo "SSL certificate already exists, using existing one."
          fi

          sudo tee /etc/nginx/sites-available/default > /dev/null << 'EOF'
          # route http requests to https
          server {
            listen 80;
            server_name *.amazonaws.com;
            return 301 https://\$host\$request_uri;
          }

          # route https from port 443 to port 8080
          server {
            listen 443 ssl;
            server_name *.amazonaws.com;

            ssl_certificate /etc/nginx/ssl/certificate.crt;
            ssl_certificate_key /etc/nginx/ssl/privatessl.key;

            location / {
              proxy_pass http://localhost:8080;
              proxy_set_header Host \$host;
              proxy_set_header X-Real-IP \$remote_addr;
            }
          }
          EOF
          '

      - name: Test and Run Nginx Proxy
        run: |
          EC2_HOST=${{ needs.terraform.outputs.ec2host }}
          ssh -o StrictHostKeyChecking=no -i innerlens-key.pem "ubuntu@$EC2_HOST" '  
            sudo nginx -t
            sudo systemctl enable nginx
            sudo systemctl restart nginx
          '

  flyway:
    name: Flyway Migrations
    permissions:
      id-token: write
      contents: read
    needs:
      - terraform
      - deploy-api
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::229582503298:role/github-oidc
          aws-region: af-south-1

      - name: Get Secrets
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: |
            DATABASE_NAME, dbname
            POSTGRESUSER, postgresuser
            POSTGRESPASSWORD, postgrespass

      - name: Run Flyway Migrations
        run: |
          docker run --rm \
            --volume ${{ github.workspace }}/migrations:/flyway/sql:ro \
            redgate/flyway \
            -url="jdbc:postgresql://${{ needs.terraform.outputs.dbhost }}/${{ env.DATABASE_NAME }}" \
            -user="${{ env.POSTGRESUSER }}" \
            -password="${{ env.POSTGRESPASSWORD }}" \
            migrate